### ISSUE TITLE
Crashing on Debian Wheezy AMD64

### ISSUE THREAD

**Issue by dilworks** [cshorler/hal-flash#1]
I hope that someone checks out this issue...

Anyway, here I go: I had recently the need to access some DRM-protected Flash video stuff, and I'm using (the new-stable) Debian Wheezy on a 64-bit CPU.

Installed hal from Debian repos, didn't liked it, promptly uninstalled it, did some googling and found your hack. Unfortunately it causes the Flash plugin to crash here as soon as it tries to load the DRM library libadobecp-whatever.so.

**Comment by P3lUZa** [comment]
Deleting ./adobe and:
$ sudo ldconfig

fixed problems for me :D
