### ISSUE TITLE
Please tag the 0.3.1 release

### ISSUE THREAD

**Issue by flexiondotorg** [cshorler/hal-flash#10]
Hi,

You might remember that I would like to get hal-flash into Debian and Ubuntu. Could you tag master with 0.3.1 so it aligns with the `debian/changelog` updates I made? Without an upstream tarball that matches the `debian/changelog` I can't get this packaged :-(

Regards, Martin.

**Comment by cshorler** [comment]
On 19 June 2015 10:23:40 BST, Martin Wimpress <notifications@github.com> wrote:
>Hi,
>
>You might remember that I would like to get hal-flash into Debian and
>Ubuntu. Could you tag master with 0.3.1 so it aligns with the
>`debian/changelog` updates I made. Without an upstream tarball that
>matches the `debian/changelog` I can't get this packaged :-(
>
>Regards, Martin.

It slipped my mind - will do today
Chris

**Comment by cshorler** [comment]
tagged!...
 also a few openSUSE related packaging fixes added and the configure.ac was updated to reflect the new version number!

**Comment by flexiondotorg** [comment]
Thank you.
