### ISSUE TITLE
Amazon Prime Video stopped working since flash 11.2.202.468 upgrade, plugin segfaults

### ISSUE THREAD

**Issue by akhuettel** [cshorler/hal-flash#11]
Amazon Prime Video stopped working since flash 11.2.202.468 upgrade, plugin segfaults

Here's a backtrace of the plugin container:

Core was generated by `/usr/lib64/firefox/plugin-container /usr/lib64/nsbrowser/plugins/libflashplayer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007f77b598c0f8 in marshal_string (pos_after=<optimized out>, byte_order=<optimized out>, value=<optimized out>, insert_at=<optimized out>, 
    str=<optimized out>) at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-basic.c:760
#2  _dbus_marshal_write_basic (str=0x7f77966e6928, insert_at=20, type=type@entry=111, value=0xa5a, byte_order=108, pos_after=0x7f77963fca00)
    at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-basic.c:840
#3  0x00007f77b597bf71 in _dbus_type_writer_write_basic_no_typecode (value=<optimized out>, type=111, writer=0x7f77963fc9e0)
    at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-recursive.c:1601
#4  _dbus_type_writer_write_basic (writer=writer@entry=0x7f77963fc9e0, type=type@entry=111, value=value@entry=0x7f77963fca80)
    at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-recursive.c:2323
#5  0x00007f77b5979795 in write_basic_field (writer=writer@entry=0x7f77963fcad0, field=field@entry=1, type=type@entry=111, 
    value=value@entry=0x7f77963fca80) at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-header.c:318
#6  0x00007f77b5979dae in _dbus_header_create (header=0x7f77966e6928, byte_order=<optimized out>, message_type=1, 
    destination=0x7f77967b8f52 "org.freedesktop.UDisks", path=0x5a5a5a5a5a5a5a5a <error: Cannot access memory at address 0x5a5a5a5a5a5a5a5a>, 
    interface=0x7f77967b8df0 "org.freedesktop.DBus.Properties", member=0x7f77967b8f4e "Get", error_name=0x0)
    at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-marshal-header.c:597
#7  0x00007f77b597e611 in dbus_message_new_method_call (destination=0x7f77967b8f52 "org.freedesktop.UDisks", 
    path=0x5a5a5a5a5a5a5a5a <error: Cannot access memory at address 0x5a5a5a5a5a5a5a5a>, iface=0x7f77967b8df0 "org.freedesktop.DBus.Properties", 
    method=0x7f77967b8f4e "Get") at /var/tmp/portage/sys-apps/dbus-1.8.16/work/dbus-1.8.16/dbus/dbus-message.c:1353
#8  0x00007f77967b8259 in _get_udisks_property (device_path=0x5a5a5a5a5a5a5a5a <error: Cannot access memory at address 0x5a5a5a5a5a5a5a5a>, 
    property_name=property_name@entry=0x7f77967b9059 "DriveConnectionInterface", ctx=<optimized out>, 
    iface_name=0x7f77967b8f30 "org.freedesktop.UDisks.Device") at libhal.c:82
#9  0x00007f77967b8bb2 in device_storage_bus (device_path=<optimized out>, ctx=<optimized out>) at libhal.c:161
#10 libhal_device_get_property_string (ctx=<optimized out>, udi=<optimized out>, key=<optimized out>, error=<optimized out>) at libhal.c:485
#11 0x00007f7796cd2086 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#12 0x00007f7796cd4a4e in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#13 0x00007f7796bb87a5 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#14 0x00007f7796c4e094 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#15 0x00007f7796d0099c in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#16 0x00007f7796d13314 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#17 0x00007f7796d16679 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#18 0x00007f7796cf5956 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#19 0x00007f7796c4dd93 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#20 0x00007f7796c4e04a in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#21 0x00007f7796b9710c in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#22 0x00007f7796c893cd in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#23 0x00007f7796c8a82b in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#24 0x00007f7796a79e81 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#25 0x00007f7796a6c13e in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#26 0x00007f7796a6d143 in ?? () from /home/huettel/.adobe/Flash_Player/NativeCache/902754B9E011F85BA521C519C8994DF9/4c04df7a/libadobecp-301806-2.so
#27 0x00007f77a8363efc in ?? () from /usr/lib64/nsbrowser/plugins/libflashplayer.so
#28 0x00007f77a836444e in ?? () from /usr/lib64/nsbrowser/plugins/libflashplayer.so
#29 0x00007f77bd5ba2c4 in start_thread (arg=0x7f77963ff700) at pthread_create.c:310
#30 0x00007f77b8523f4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 

More info on request

**Comment by akhuettel** [comment]
No idea what happens, lines 8-10 are in libhal, so sending this here for review...

**Comment by cshorler** [comment]
On 27 June 2015 19:47:14 BST, "Andreas K. Hüttel" <notifications@github.com> wrote:
>No idea what happens, lines 8-10 are in libhal, so sending this here
>for review...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cshorler/hal-flash/issues/11#issuecomment-116116587

Can you check udisks /² is running (dbus active) you can use qdusviewer to confirm.  I'll be unable to investigate until next week - is there an easy way to test Amazon Prime?

Chris

**Comment by cshorler** [comment]
are you still seeing this?

**Comment by akhuettel** [comment]
It disappeared at some point, for no clear reason. 
Can't test it anymore since Prime Video stopped supporting Flash in the meantime.
