### ISSUE TITLE
Hulu Stopped Playing on OpenSUSE 12.3 and 13.1

### ISSUE THREAD

**Issue by 6sn7** [cshorler/hal-flash#13]
I'm looking for help getting hulu (standard) playing again on OpenSUSE (ads play fine but the content just shows up blank with the 'play button' greyed out.
Hulu customer support said I need to install libhal due to DRM and so here I am.

I downloaded hal-flash and autoconf fails with the following error:

autoconf -i
configure.ac:21: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

It builds 'configure' but that fails if I tried to invoke it as follows:

./configure
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
./configure: line 1754: syntax error near unexpected token `-Wall'
./configure: line 1754: `AM_INIT_AUTOMAKE(-Wall -Wno-extra-portability -Werror foreign)'

I managed to build the libhal.so from the src but don't know where to install the lib.
Putting it into my LD_LIBRARY_PATH or in the system lib dir /usr/lib64 doesn't help.

I'm running the following:

OpenSUSe 12.3
Firefox 34.0.5
flash-player-11.2.202.440-2.115.1.x86_64

Pointers/suggestions will be appreciated.

Thanks.

**Comment by cshorler** [comment]
On 18 August 2015 12:05:16 BST, John Kichury <notifications@github.com> wrote:
>I'm looking for help getting hulu (standard) playing again on OpenSUSE
>(ads play fine but the content just shows up blank with the 'play
>button' greyed out.
>Hulu customer support said I need to install libhal due to DRM and so
>here I am.
>
>I downloaded hal-flash and autoconf fails with the following error:
>
>autoconf -i
>configure.ac:21: error: possibly undefined macro: AM_INIT_AUTOMAKE
>  If this token and others are legitimate, please use m4_pattern_allow.
>      See the Autoconf documentation.
>
>It builds 'configure' but that fails if I tried to invoke it as
>follows:
>
>./configure
>configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
>./configure: line 1754: syntax error near unexpected token `-Wall'
>./configure: line 1754: `AM_INIT_AUTOMAKE(-Wall -Wno-extra-portability
>-Werror foreign)'
>
>I managed to build the libhal.so from the src but don't know where to
>install the lib.
>Putting it into my LD_LIBRARY_PATH or in the system lib dir /usr/lib64
>doesn't help.
>
>I'm running the following:
>
>OpenSUSe 12.3
>Firefox 34.0.5
>flash-player-11.2.202.440-2.115.1.x86_64
>
>Pointers/suggestions will be appreciated.
>
>Thanks.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cshorler/hal-flash/issues/13

I'll have to grab a vm to check 12.3, I don't have any machines running it any more.

What's in the m4 directory?

What's the output of 
$ git status

(Did autoreconf create any files)

**Comment by 6sn7** [comment]
m4 directory is empty.
autoconf created autom4te.cache/ directory and configure.

git status outputs the following: (note, I simply downloaded and extracted the zip file which created the 'hal-flash-master' directory.)  cd to hal-flash-master and issuing 'git status':
fatal: Not a git repository (or any of the parent directories): .git

autoreconf outputs the following:

autoreconf
configure.ac:42: error: required file './config.guess' not found
configure.ac:42:   'automake --add-missing' can install 'config.guess'
configure.ac:42: error: required file './config.sub' not found
configure.ac:42:   'automake --add-missing' can install 'config.sub'
configure.ac:21: error: required file './install-sh' not found
configure.ac:21:   'automake --add-missing' can install 'install-sh'
configure.ac:42: error: required file './ltmain.sh' not found
configure.ac:21: error: required file './missing' not found
configure.ac:21:   'automake --add-missing' can install 'missing'
src/Makefile.am: error: required file './depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1

**Comment by cshorler** [comment]
I don't see this here problem here.

note that you need to run (as per the INSTALL file)
`$ autoreconf -i`

NOT
`$ autoconf -i` as you seem to have done initially, possibly also explaining the absence of files in the m4 directory

**Comment by 6sn7** [comment]
Thank you for taking the time to point out my error. I should have noticed 'autoreconf' and not 'autoconf'.
Hulu content now plays fine.
