### ISSUE TITLE
test/flash.c segfaults after getting empty processor list

### ISSUE THREAD

**Issue by afbarnard** [cshorler/hal-flash#14]
I was trying to see if I had correctly installed libhal, but your test program, test/flash.c, segfaults after getting an empty processor list.

This line in `flash.c` is where it happens because `processor_list` is `NULL`.

    while (processor_list[i] != NULL) {

The processor list is NULL because `libhal_manager_find_device_string_match` (in libhal.c) only currently handles storage devices and not the requested information on processors, so it falls to the else clause which assigns a NULL return value via g_strdupv:

    hal_device_names = g_strdupv(default_r_val);

This makes me think that `libhal_manager_find_device_string_match` and/or `flash.c` is incomplete.

Thanks for looking into this and providing any advice on how to (alternatively) test if libhal is correctly installed and working.

**Comment by cshorler** [comment]
On 25 August 2015 04:07:57 BST, Aubrey Barnard <notifications@github.com> wrote:
>I was trying to see if I had correctly installed libhal, but your test
>program, test/flash.c, segfaults after getting an empty processor list.
>
>This line in `flash.c` is where it happens because `processor_list` is
>`NULL`.
>
>    while (processor_list[i] != NULL) {
>
>The processor list is NULL because
>`libhal_manager_find_device_string_match` (in libhal.c) only currently
>handles storage devices and not the requested information on
>processors, so it falls to the else clause which assigns a NULL return
>value via g_strdupv:
>
>    hal_device_names = g_strdupv(default_r_val);
>
>This makes me think that `libhal_manager_find_device_string_match`
>and/or `flash.c` is incomplete.
>
>Thanks for looking into this and providing any advice on how to
>(alternatively) test if libhal is correctly installed and working.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cshorler/hal-flash/issues/14

I've not checked recently, but flash didn't require this last time I checked.  What are you trying to do?

**Comment by afbarnard** [comment]
I was trying to test libhal, which seems to work, at least as much as my modifications of test/flash.c can test. Further, flash appears to work with your libhal, modulo some SELinux issues. (Hulu has recently activated flash DRM on Linux, which requires HAL, but Fedora no longer supports HAL, thus your libhal.)

The reason I created this issue is that your test program, test/flash.c, always crashes as written. This is not very intuitive for a test program for your library. Perhaps I am misinterpreting the purpose of test/flash.c, or perhaps something else is going on, but I thought you might want to fix your test program.

**Comment by cshorler** [comment]
to explain:
This behaviour was deliberate - the plugin still works if it receives nothing back when querying the cpu.  

I chose the minimum impact of fix in line with what I remember about the required behaviour.

FYI the flash.c mimics the flash plugin API calls (well as of several years ago - it's probably still accurate, since they haven't removed the dependency on libhal)

**Comment by cshorler** [comment]
Actually this is a good spot - because it's possible it explains some other bad behaviour.
