### ISSUE TITLE
DRM content only plays after doing "TESTING INSTALLATION" from README

### ISSUE THREAD

**Issue by lucianm** [cshorler/hal-flash#15]
Hi,

first of all, thank you so much for providing this, it saved me from advising my wife to use Windows on her laptop when she wants to watch some TV shows which are available also online at the TV station's web pages.

Actually, I noticed this also after I found hal-flash and installed it, when just trying to playback some DRM content, the behaviour is that only the non-protected commercials at the beginning play, and then the actual protected content displays the circle animation forever. The normal reaction of someone who installed hal-flash (so obviously not of the actual user to which the system belongs, my wife, who just tells me "doesn't work, again") is to read again the README, and after finding out that the Adobe test video actually works, to wonder how is that possible.
Well, just trying again to watch other protected content, then works, and now I have the belief this is connected to the testing. I did not yet fully analyze if it still works if the browser (Firefox) is closed and started again, but will check.
Can you reproduce something like that as well, do you have any idea why this is happening? If you want to test, please try something like this: http://www.vox.de/cms/sendungen/shopping-queen.html or this: http://www.rtl.de/cms/sendungen/tv-videos.html (Ad-blocker should be disabled on the respective page)

Greetings,
Lucian

**Comment by cshorler** [comment]
Generally with such problems it seems linked to flash having cached data prior to having any libhal installed.  So I wouldn't be surprised if it worked first time on a new user account if you used the flash GUI (KDE / QT / GTK tools usually provided as an auxiliary package to the plugin) to clear the cache [ NO need to delete licence files as far as I'm aware]

**Comment by cshorler** [comment]
I tested the above links - none of them work beyond the adverts for me, perhaps there's a restriction due to my location.  It now occurs to me I see a similar issue with Channel 5 in the UK, which I think is owned by RTL - perhaps they have the same people doing their serving.  Here it's resolved by pressing refresh once.  I suspect there's a bug in the server sending the checkpoint library the first time.

**Comment by lucianm** [comment]
At my side, I cleared all Firefox cache and manually deleted the ~/.adobe directory where Flash Player stores its stuff. Then again, I could only make it play after briefly playing the test video. That one seems to be non-problematic, and yet triggering something, like having the client cache something needed also by content from other servers. Well, it's a bit strange.

**Comment by conchurnavid** [comment]
Here are my notes from other installations (you already did most of them). Maybe you can still try the rest:

* uninstall hal
* install libhal1-flash
* Disable Adblocker and Tracker-Blocker (Adblock, Adblock Plus, Ghostery, Privacy Badger, ...)
* Disable Script-Blocker (NoScript, ...)
* Disable HTTPS-Everywhere
* Enable Third-Party Cookies (at least for this site)
* Enable Plugins for this site
* Use Firefox/Iceweasel (chrome/chromium with pepperflash doesn't support DRM)
* Don't use inkognito mode
* Remove Flash cache folders
  * rm -rf ~/.macromedia
  * rm -rf ~/.adobe
  * rm -rf ~/.config/google-chrome/Default/Pepper\ Data/
  * rm -rf ~/.config/chromium/Default/Pepper\ Data/
 * Restart your browser

After these steps I could always use VOX and RTL media players on Debian Jessie amd64

**Comment by cshorler** [comment]
Some of this is necessary some of shouldn't be necessary - perhaps we should add it to the readme / faq
