### ISSUE TITLE
Possible to remove udisks dependacy?

### ISSUE THREAD

**Issue by cb88** [cshorler/hal-flash#16]
Udisks has started requiring JavaScript as a build dependency due to polkit... suffice to say it's a mess.

It would be nice if hal-flash was self contained which doesn't seem too far fetched since hal-flash already seems quite small and only does a limited number of things like report disk serial, size and such.

**Comment by cshorler** [comment]
I haven't had a chance to look yet, is that a build time only dependency or a run time dependency?

Generally I don't agree with this idea and prefer to keep the dependency on udisks2 or some busybox clone for embedded devices.

**Comment by cb88** [comment]
An embedded version would be vastly preferable... 

They are talking in about using duktape in polkit... But overall even the polkit developers themselves don't all like JavaScript rules and have talked about reverting to the old declarative rules engine. I believe is is required whever the rules are rebuilt so its an optional runtime dependency that things like network manager require?

**Comment by ehegnes** [comment]
I hacked at a version of `udisks` a while back to remove the {console,policy}kit dependency ([ehegnes/udisks-kitless](https://github.com/ehegnes/udisks-kitless)). It's quite an ugly bit of finagling, but maybe you could try something similar?

**Comment by cshorler** [comment]
I'm not sure I've been well understood here initially - I mean for someone to submit buildroot patches for udisks (not to develop libhal).

**Comment by ehegnes** [comment]
@cshorler would you please elaborate on the purpose for submitting buildroot patches?

The buildroot to which you are referring is [`maximeh/buildroot`](https://github.com/maximeh/buildroot), yes?

**Comment by cshorler** [comment]
The only reason for modifying udisks (in my opinion!) is if you can't live with it's dependencies.  

I thought one case would be building an embedded system (which I've done with buildroot several times - best way in my opinion).  
https://git.busybox.net/buildroot/
or
buildroot.org

The other case would be if you're contributing to udisks  or forking it (but then why raise an issue here)

Am I missing something?
