### ISSUE TITLE
Install instrucions are not clear enough

### ISSUE THREAD

**Issue by P3lUZa** [cshorler/hal-flash#17]
I think build instructions should start with the development mode, instead of a ./configure command, since people who read this are the ones who cloned the git code, so when you read quickly you only see a no sense ./configure at first. I think it should be something like:

Development (only applies to a git cloned tree):

1. Prerequisites: autoconf, libtool, C compiler, ... (i.e. you need a standard development base system).
2. autoreconf -i
3. ./configure
4. make
5. make install
6. ldconfig

Build Instructions:

1. Install this package
   ./configure --prefix=...
   make
   make install DESTDIR=...
   
Packaging:
1. Ensure the HAL package (daemon, library etc) is not installed and ideally
   conflicts with this package.
2. The flash package could recommend this package for drm content.

**Comment by cshorler** [comment]
People may download a release tarball (not everyone has access to a package).  There is normally no need to clone unless you are planning to patch something.

When I'm developing i normally set LD_LIBRARY_PATH, as outlined in TESTING.

I will add ldconfig to non-development instructions and change the development instructions to reflect TESTING.

Regarding the other point (gotchas), there's already a issue on it - I need to document what's valid.

**Comment by P3lUZa** [comment]
I couldn't find a tarball for it but I did find a deb package on launchpad. However it was funny since I installed it with the deb file in my two computers (32 bits and 64bits) and they both worked on DRM sites, then I visited another DRM site and the 32 bits computer worked while the 64 bits crashed, so I decided to compile the git source code ... flash didn't work until I deleted .mozilla, .adobe, .macromedia and $ ldconfig. Now both computers are working :smiley:
