### ISSUE TITLE
silverlight trending?

### ISSUE THREAD

**Issue by splace** [cshorler/hal-flash#18]
"Since HAL is no longer centric to most modern Linux systems (now we have UDev,
UDisks etc) - I'm only really providing this library because I see a growing
trend in the UK: ITV, Lovefilm and others are now using Silverlight rather than
Flash for their drm streams.  Currently Silverlight DRM protected content isn't
supported on Linux (I'd like to see this change - I have nothing against Silverlight)."

just got 0.3.2, where in its comments it says above, AFAIK ITV dumped silverlight 5 years ago, and i was getting the strong impression that the silverlight trend has been down ever since, and had basically missed the bus, HTML5 however seems on the rise, just saying.

**Comment by cshorler** [comment]
quite true, the text was written a long time ago... I'll fix it now!  (also Mono project seems to be discontinued as well)
