### ISSUE TITLE
Missing automake-1.13? 

### ISSUE THREAD

**Issue by jazzgroove** [cshorler/hal-flash#24]
Hello,

Is there any reason I can't build this with automake-1.14 on Debian/jessie? What do I need to modify? I'm getting the following:

/dev/src/hal-flash/missing: line 81: automake-1.13: command not found
WARNING: 'automake-1.13' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
Makefile:330: recipe for target 'Makefile.in' failed
make: **\* [Makefile.in] Error 1

Thanks in advance for any advice!

**Comment by jazzgroove** [comment]
Sorry, I figured this out. Needed to run automake with my version. Running the following fixed the issue:

aclocal
automake 
./configure

Perhaps we can add to the INSTALL

**Comment by mxjWilliam** [comment]
helped me a lot ,thanks

**Comment by sanbrother** [comment]
> Sorry, I figured this out. Needed to run automake with my version. Running the following fixed the issue:
> 
> aclocal automake ./configure
> 
> Perhaps we can add to the INSTALL

`autoreconf -is` also works
