### ISSUE TITLE
package dbus-1 not found

### ISSUE THREAD

**Issue by avodonosov** [cshorler/hal-flash#5]
```
$ ./configure --prefix=

....

checking for DBUS... no
configure: error: Package requirements (dbus-1 >= 0.61) were not met:

No package 'dbus-1' found
```

**Comment by cshorler** [comment]
searching the debian package list shows libdbus-1-dev

However, I think if you update / pull the last set of commits (from this morning) you'll find that the libglib fixes will probably also resolve this problem.

**Comment by georgegoldman** [comment]
hi 
i get this when i run my this ---> $ sudo apt-get install dbus-devel

N: Ignoring file 'pgdg.list.save.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to locate package dbus-devel
